//
// Created by Lennert Steyaert on 06/05/2022.
//

#ifndef DOOM_QUAKE_ETEXTURE_H
#define DOOM_QUAKE_ETEXTURE_H

enum ETexture {
    AWESOMEFACE = 0,
    // AWESOMEFACE_NORMAL= 1,
    STONE = 1,
    GRASS = 2,
    METAL = 3,
    CONCRETE = 4,
    WOODFLOOR = 5,
    DOORWALL = 6,
    CONTAINER = 7,
    WALL = 8,
    WALL_NORMAL = 9,
    WOODFLOOR_NORMAL = 10,
    DUNGEON = 11,
    DUNGEONNORMAL = 12,
    DOORWALLNORMAL = 13,
    SPACEMETAL = 14,
    SPACEMETALNORMAL = 15,
    METALTWO = 16,
    METALTWONORMAL = 17,
    METALTHREE = 18,
    METALTHREENORMAL = 19
};

#endif //DOOM_QUAKE_ETEXTURE_H
